server:
  port: 8080
  tomcat:
    accept-count: '500'
    connection-timeout: 2000
    max-connections: '10000'
    max-http-post-size: 2MB
    max-threads: '200'
    min-spare-threads: '10'
    max-swallow-size: 2MB

spring:
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: consumer-group-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    producer:
      compression-type: gzip
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  messages:
    basename: messages
    fallback-to-system-locale: false
    encoding: UTF-8
  output:
    ansi:
      enabled: ALWAYS